#!/bin/bash
set -e
FULL_PARAMS="$1"
ACTION="${FULL_PARAMS%%,*}"
PARAMS_REST="${FULL_PARAMS#*,}"
[[ -n "$PARAMS_REST" && "$PARAMS_REST" != "$FULL_PARAMS" ]] && while IFS='=' read -r key val; do [[ -n "$key" ]] && export "$key=$val"; done <<< "${PARAMS_REST//,/$'\n'}"
RED='\033[0;31m'; GREEN='\033[0;32m'; NC='\033[0m'
log_info() { printf "${GREEN}✓${NC} %s\n" "$1"; }; log_error() { printf "${RED}✗${NC} %s\n" "$1"; exit 1; }
detect_os() { source /etc/os-release || log_error "Cannot detect OS"; OS_DISTRO="${ID,,}"; case "$OS_DISTRO" in ubuntu|debian|raspbian|linuxmint|pop) PKG_UPDATE="apt-get update"; PKG_INSTALL="apt-get install -y"; PKG_UNINSTALL="apt-get remove -y" ;; fedora|rhel|centos|rocky|alma) PKG_UPDATE="dnf check-update || true"; PKG_INSTALL="dnf install -y"; PKG_UNINSTALL="dnf remove -y" ;; arch|manjaro|endeavouros) PKG_UPDATE="pacman -Sy"; PKG_INSTALL="pacman -S --noconfirm"; PKG_UNINSTALL="pacman -R --noconfirm" ;; opensuse*|sles) PKG_UPDATE="zypper refresh"; PKG_INSTALL="zypper install -y"; PKG_UNINSTALL="zypper remove -y" ;; alpine) PKG_UPDATE="apk update"; PKG_INSTALL="apk add"; PKG_UNINSTALL="apk del" ;; *) log_error "Unsupported distribution: $OS_DISTRO" ;; esac; }
case "$ACTION" in install) log_info "Installing Proxmox..."; detect_os; sudo $PKG_UPDATE || true; sudo $PKG_INSTALL  || log_error "Failed"; sudo systemctl enable proxmox 2>/dev/null || true; sudo systemctl start proxmox 2>/dev/null || true; log_info "Proxmox installed!" ;; update) log_info "Updating Proxmox..."; detect_os; sudo $PKG_UPDATE || true; sudo $PKG_INSTALL  || log_error "Failed"; sudo systemctl restart proxmox 2>/dev/null || true; log_info "Proxmox updated!" ;; uninstall) log_info "Uninstalling Proxmox..."; detect_os; sudo systemctl stop proxmox 2>/dev/null || true; sudo systemctl disable proxmox 2>/dev/null || true; sudo $PKG_UNINSTALL  || log_error "Failed"; log_info "Proxmox uninstalled!" ;; config) log_info "Proxmox configuration"; log_info "See documentation for details" ;; *) log_error "Unknown action: $ACTION" ;; esac
